BanklessDAO/bankless-website

components/common/page-container.tsx
components/common/three-rings.tsx
components/common/underline.tsx
components/home/card.tsx
components/home/section1.tsx
components/home/section2.tsx
components/home/section3.tsx
components/home/section4.tsx
components/home/section5.tsx
config/theme.ts

- Improved design of the Page
- Made the Whole Page responsive for all screen sizes
- Added gradient in backgrounds
- Added new gradient underline and updated old underline
- Adjusted Font sizes, the width of texts
- Also Adjusted the width and height of Videos and Images
- Improved Layouts of all image groups

May PR24: 16hr - Completed the overall refactoring of the Homepage

---

components/about-us/sub-pages/guilds/guild.tsx
components/about-us/sub-pages/guilds/section.tsx
config/theme.ts
yarn.lock

make changes has specified, using the ui design has reference

About us guild

---

components/about-us/sub-pages/guilds/guild.tsx
components/about-us/sub-pages/guilds/section.tsx
components/invest/BankSection.tsx
components/invest/BedIndex.tsx
components/invest/DaoPunkSection.tsx
components/invest/GmiIndex.tsx
components/invest/NftInvest.tsx
config/theme.ts
yarn.lock

fixed the button alignment, fixed NFT invest section flex responsiveness. Added background glow where needed to the about-us guild section.

About us invest page

---

components/_common/nav-bar.tsx

Updated the brand logo to be larger in the nav bar.  Added hover effects for nav links, and fixed issue with mobile menu loading links in row on large mobile screens.

Nav bar fixes

---

components/_common/Logo.tsx
components/_common/nav-bar.tsx
components/_common/underline.tsx
components/home/Snapshot/Column.tsx
components/home/Snapshot/Proposal.tsx
components/home/Snapshot/ProposalList.tsx
components/home/Snapshot/SnapshotSection.tsx
components/home/Snapshot/TimeLeft.tsx
components/home/Snapshot/VoteInfo.tsx
components/home/index.tsx
components/utils/snapshot.ts

Added section to replace treasury.  New section pulls data from snapshot api to show the 5 most recent votes.  Shows the live vote info.

Snapshot section

---

assets/content/pages/work-with-us/carouselContent.json
components/home/section2.tsx
components/read/international-media-node.tsx

Fix: typos

---

components/about-us/sub-pages/projects/content.tsx
components/about-us/sub-pages/projects/content/infosec-team.tsx

Add InfoSec Team to Projects page

---

pages/_app.tsx

feat: add google analytics

---

components/listen/podcasts.tsx
pages/_app.tsx

Closes [Dework 158](https://app.dework.xyz/banklessdao-1/website-project-2/view/board-5609?taskId=37b4bc25-2444-4cd3-a6e0-d2d80bb0863e)
Changes:
- Update dead links
- Update podcast description
- Add _blank targets for users not to quit the page when clicking a link

fix: updated dead links, podcast description, add _blank target

---

.github/CODEOWNERS

fix: Syntax error, Remove Website team from CODEOWNERS

---

components/_common/footer.tsx

Fixes https://app.dework.xyz/banklessdao-1/website-project-2?taskId=d04c901d-8c53-4562-9856-e9ec647aae9a

fix: instagram link in footer

---

components/_common/nav-bar.tsx

Implement 2 req: 
1, Highlight with **red** border the page your are currently on.
2, use **white** border when hovering.

feat: improve menu context (dw-137)

---

components/about-us/sub-pages/nodes/international-media-nodes.tsx
components/about-us/subnav.tsx
components/new-members/join.tsx

Fixes [dw-106](https://app.dework.xyz/banklessdao-1/website-project-2?taskId=55dea5d6-4b80-4f44-b1e0-809bb4c49527)
Changes:

fix(dw-106): international media nodes

---

components/listen/podcasts.tsx

Closes #122
Fixes [dw-183](https://app.dework.xyz/banklessdao-1/website-project-2?taskId=d0df929b-8654-4581-9e44-d9858cbba28b)

fix(dw-183): making bank

---

components/work-with-us/Carousel.tsx

Fixes [dw-151](https://app.dework.xyz/banklessdao-1/website-project-2?taskId=79b5a152-a68c-48ac-af78-5f32187b3a59)

fix: tabs UX on mobile

---

components/_common/nav-bar.tsx

Fixes [dw-96](https://app.dework.xyz/banklessdao-1/website-project-2?taskId=b20c2280-0cc8-4386-8e64-a8daddf997d4)

fix: menu item bounce (dw-96)

---

components/invest/BankSection.tsx
components/invest/BedIndex.tsx
components/invest/DaoPunkSection.tsx
components/invest/GmiIndex.tsx
components/invest/NftInvest.tsx

Fixes [dw-147](https://app.dework.xyz/banklessdao-1/website-project-2?taskId=2a3f2cac-3c8b-475a-8edc-6c7950cbf380)

fix: buttons underline on hover

---

components/about-us/sub-pages/Governance/season.tsx
components/about-us/sub-pages/Governance/start.tsx

Fixes [dw-142](https://app.dework.xyz/banklessdao-1/website-project-2?taskId=6963a487-8369-4df4-a1f3-480150d30150)

fix: buttons hover and buy bank text hover

---

components/home/card.tsx

Fixes [dw-131](https://app.dework.xyz/banklessdao-1/website-project-2?taskId=51f174bc-5060-4d76-82bc-a992c6c90554)

feat: make cards clickable

---

components/invest/DaoPunkSection.tsx

Fixes [dw-148](https://app.dework.xyz/banklessdao-1/website-project-2?taskId=d1a0361f-c06c-4914-a620-6959c404746a)

fix: maintain daopunks aspect ratio at all screen sizes (dw-148)

---

.gitignore

Fixes [dw-153](https://app.dework.xyz/banklessdao-1/website-project-2?taskId=900eb6c1-bf61-4be9-bd78-8c7bc904e56c)
* Purge and Ignore `cypress/downloads`, `cypress/screenshots`, and `cypress/videos`
> **Warning**: Changing public git history invalidated all downstream forks and local clones. Please re-create or force-sync your downstream forks and local clones! Apologies for the inconvenience.
Alongside this PR, I used [BFG Repo-Cleaner](https://rtyley.github.io/bfg-repo-cleaner/) to purge the aforementioned directories from the git history. It's as if they were never committed to the repository in the first place.
<details>
<summary>BFG Repo-Cleaner Console Log</summary>
```console
mantisclone@mantisclone-Inspiron-7620:~/projects$ git clone --mirror …
```

fix: Ignore cypress downloads, screenshots, and videos (dw-153)

---

components/invest/DaoPunkSection.tsx

fixes [dw-148](https://app.dework.xyz/banklessdao-1/website-project-2?taskId=d1a0361f-c06c-4914-a620-6959c404746a)

`fix: dao punks image width (dw-148)`

---

components/home/card.tsx

fixes [dw-133](https://app.dework.xyz/banklessdao-1/website-project-2?taskId=eacbe0b3-3b5d-4f6b-a237-9f1300c057f7)

`fix: fix card ratio on mobile (dw-133)`

---

components/home/section1.tsx

Fixes [dw-128](https://app.dework.xyz/banklessdao-1/website-project-2?taskId=1b3c9f7b-d930-4ea0-8b6a-3bcbe9c30dd2)

`fix: Add Join Us call-to-action and Learn More links on homepage (dw-128)`

---

components/home/index.tsx

Fixes [dw-163](https://app.dework.xyz/banklessdao-1/website-project-2?taskId=9318eea1-8577-44de-bd1c-92297539a3ae)

`Fix: fix the broken subscribe button on the home page (dw-193)`

---

components/about-us/sub-pages/projects/content.tsx
components/about-us/sub-pages/projects/content/governator.tsx

Fixes [dw-205](https://app.dework.xyz/banklessdao-1/website-project-2?taskId=1657a1df-3fa6-4dbc-a470-66505d3e5114)

`fix: add governator to projects section (dw-205)`

---

components/about-us/sub-pages/projects/content/governator.tsx

Fixes https://github.com/BanklessDAO/bankless-website/pull/185#discussion_r1270950562

fix: governator copy

---

components/home/section2.tsx

Fixes [dw-211](https://app.dework.xyz/banklessdao-1/website-project-2?taskId=7a829269-af42-471f-a969-5e4557527b70)

chore: Replace COMING HOME card with DEPARTMENTS card on home page

---

components/_common/nav-bar.tsx

* Add external Governance and Token Dashboard

feat: add dashboard

---

components/_common/nav-bar.tsx

feat: add rewards page

---

components/_common/nav-bar.tsx

Fixes [dw-239](https://app.dework.xyz/banklessdao-1/website-project-2?taskId=b4d46670-7865-42a6-9b1b-3d2ebb3c8f53)
Proposed Menu Bar:
* Home
* About Us
* Departments
* Projects
* Guilds
* Read
* Listen
* Media Nodes
* Work with Us
* Join Us
* Community Calls
* Onboarding
* Rewards
* Governance
* Dashboard
* Token
* Lock BANK

fix: menu bar (dw-239)

---

components/_common/footer.tsx
components/about-us/introduction.tsx
components/about-us/sub-pages/Governance/intro.tsx
components/about-us/sub-pages/Governance/start.tsx
components/home/section1.tsx
components/join-us/join.tsx
components/listen/podcast-idea.tsx
components/token/Disclaimer.tsx

A likely scammer is using the old Discord link
* Change the old Discord link to the new Discord link: https://discord.gg/blackflagdao
* Automatically reformat the Disclaimer

chore: Update Discord link from bankless to blackflagdao
